#!/bin/bash

CSC=cscope
CSFILES=$CSC.files
CSOUT=$CSC.out
EXTS="[cC] [cC][cC] [cC][pP][pP] [hH] [hH][pP][pP] php PHP js JS java JAVA lua pl make mak sh"
FILES="Makefile CMakeLists.txt"

rm -f $CSFILES $CSOUT
for EXT in $EXTS
do
	find . -name "*.$EXT" >> $CSFILES
done
for FILE in $FILES
do
	find . -name "$FILE" >> $CSFILES
done
sed -i 's#.*#"&"#g' $CSFILES
cscope -Rb
